### ISSUE TITLE
Errors running last 'Getting started' example

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#128]
I ran into a few issues running the very last example on the Getting started page of the documentation.
https://cocktail-shaker.readthedocs.io/en/latest/guide/quickstart.html

from peptide_builder import PeptideBuilder
from functional_group_enumerator import Cocktail

should be replaced by

from cocktail_shaker import PeptideBuilder
from cocktail_shaker import Cocktail

After these changes I got the following error:

(joss3) C:\Users\olive\Google Drive\Work\joss>python test05.py
Generating 5040 Compounds...
Traceback (most recent call last):
  File "test05.py", line 13, in <module>
    dataframe.to_hdf('data.h5', key='s', mode='w')
  File "C:\Users\olive\anaconda3\envs\joss3\lib\site-packages\pandas\core\generic.py", line 2530, in to_hdf
    pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "C:\Users\olive\anaconda3\envs\joss3\lib\site-packages\pandas\io\pytables.py", line 276, in to_hdf
    path_or_buf, mode=mode, complevel=complevel, complib=complib
  File "C:\Users\olive\anaconda3\envs\joss3\lib\site-packages\pandas\io\pytables.py", line 484, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\olive\anaconda3\envs\joss3\lib\site-packages\pandas\compat\_optional.py", line 93, in import_optional_dependency
    raise ImportError(message.format(name=name, extra=extra)) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

After installing tables the code worked fine.

**Comment by Sulstice** [comment]
Ah, that is a pandas dependency that isn't installed for hd5 files. I will make a note in the docs to run this example install pandas with tables. I don't think it would be right to have it a dependency on my package.
